export const data = [
  {
    id: 1,
    name: "Events Calendar",
    image: "./img/calendar.jfif",
    site: "https://events-calendar-andurebel.netlify.app/",
    code: "https://github.com/andurebel/events-calendar-react",
    description: "Events calendar in React",
  },
  ,
  {
    id: 1,
    name: "Image Search App",
    image: "./img/search.jfif",
    site: "https://pixabay-images-andurebel.netlify.app/",
    code: "https://github.com/andurebel/image-gallery-react",
    description: "Image search app  Pixabay API",
  },
  {
    id: 2,
    name: "Countdown timer",
    image: "./img/clock.jfif",
    site: "https://countdowntimer-andurebel.netlify.app/",
    code: "https://github.com/andurebel/CountdownTimer",
    description: "Countdown timer until user input",
  },
  {
    id: 3,
    name: "Expense tracker",
    image: "./img/expense.jpg",
    site: "https://expensetracker-andurebel.netlify.app/",
    code: "https://github.com/andurebel/Expense_tracker",
    description: "Local storage expense tracker",
  },
  {
    id: 4,
    name: "Cool cards",
    image: "./img/expanding-cards.jfif",
    site: "https://expandingcards-andurebel.netlify.app/",
    code: "https://github.com/andurebel/expanding-cards",
    description: "Expanding cards cool CSS effect",
  },
  {
    id: 5,
    name: "Pokedex",
    image: "./img/pokemon.jfif",
    site: "https://pokedex-andurebel.netlify.app/",
    code: "https://github.com/andurebel/pokedex",
    description: "Pokemon information ",
  },
  {
    id: 6,
    name: "Chuck Norris Jokes",
    image: "./img/chuck-norris.jfif",
    site: "https://chucknorris-andurebel.netlify.app/",
    code: "https://github.com/andurebel/chuck-norris-jokes",
    description: "Random dad jokes generator",
  },
  {
    id: 6,
    name: "Progress Steps",
    image: "./img/progress.jpg",
    site: "https://progress-steps-andurebel.netlify.app/",
    code: "https://github.com/andurebel/progress-steps",
    description: "Click the bullets to see  progress",
  },
];
